### ISSUE TITLE
Error with entry NPA005946

### ISSUE THREAD

**Issue by mmzdouc** [NPAtlas/npatlas_website#16]
Affected entry: 
[NPA005946](https://www.npatlas.org/explore/compounds/NPA05946)
Cross-reference to MIBiG: https://github.com/mibig-secmet/mibig-json/issues/312

Problem:
Microcin J25 is not a head-to-tail cyclicized peptide but a lassopeptide. The structure in entry NPA005946 is the originally reported structure, which was corrected in [Wilson et al](doi.org/10.1021/ja036756). The correct structure can be found on [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/57397977) (visually compared against Wilson et al and confirmed).

**Comment by rlinington** [comment]
Hi @mmzdouc,

Thanks very much for raising this correction. We are actively curating structure reassignments for the next release, so I will add this to the set to be corrected in the database. In the future it would be super if you could also submit these issues through the Additions/corrections section of the website so that they get added to the pool of corrections that we address before each release.
